steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/cloudops-labs/github-olivierpilotte-gcp:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/cloudops-labs/github-olivierpilotte-gcp:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - demo-deployment
  - demo-container=gcr.io/cloudops-labs/github-olivierpilotte-gcp:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=opilotte-test'
