steps:
- name: 'build docker image'
  args: ["build", "-t", "gcr.io/cloudops-labs/github-olivierpilotte-gcp:$REVISION_ID", "."]
- name: 'push docker image to registry'
  args: ["push", "gcr.io/cloudops-labs/github-olivierpilotte-gcp:$REVISION_ID"]
- name: 'update kubernetes deployment'
  args:
  - set
  - image
  - deployment
  - demo-deployment
  - demo-container=gcr.io/cloudops-labs/github-olivierpilotte-gcp:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=opilotte-test'
